# Site settings
title: MY BLOG
url: "https://woonho0605.github.io"     # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/woonho3.github.io" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  20223089 백운호

# Your information
email: bwh0605@kookmin.ac.kr
author: Woonho
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: 20223089 백운호
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "https://bwh0605@kookmin.ac.kr"
  GitHub: "https://github.com/woonho0605"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->


permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
